// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtocolServerToClient.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ProtocolServerToClient_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ProtocolServerToClient_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ProtocolServerToClientEnum.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ProtocolServerToClient_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ProtocolServerToClient_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ProtocolServerToClient_2eproto;
namespace ProtocolServerToClient {
class ResultCreateAccount;
struct ResultCreateAccountDefaultTypeInternal;
extern ResultCreateAccountDefaultTypeInternal _ResultCreateAccount_default_instance_;
class ResultLogin;
struct ResultLoginDefaultTypeInternal;
extern ResultLoginDefaultTypeInternal _ResultLogin_default_instance_;
}  // namespace ProtocolServerToClient
PROTOBUF_NAMESPACE_OPEN
template<> ::ProtocolServerToClient::ResultCreateAccount* Arena::CreateMaybeMessage<::ProtocolServerToClient::ResultCreateAccount>(Arena*);
template<> ::ProtocolServerToClient::ResultLogin* Arena::CreateMaybeMessage<::ProtocolServerToClient::ResultLogin>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ProtocolServerToClient {

// ===================================================================

class ResultLogin final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ProtocolServerToClient.ResultLogin) */ {
 public:
  inline ResultLogin() : ResultLogin(nullptr) {}
  ~ResultLogin() override;
  explicit PROTOBUF_CONSTEXPR ResultLogin(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ResultLogin(const ResultLogin& from);
  ResultLogin(ResultLogin&& from) noexcept
    : ResultLogin() {
    *this = ::std::move(from);
  }

  inline ResultLogin& operator=(const ResultLogin& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResultLogin& operator=(ResultLogin&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ResultLogin& default_instance() {
    return *internal_default_instance();
  }
  static inline const ResultLogin* internal_default_instance() {
    return reinterpret_cast<const ResultLogin*>(
               &_ResultLogin_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ResultLogin& a, ResultLogin& b) {
    a.Swap(&b);
  }
  inline void Swap(ResultLogin* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResultLogin* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ResultLogin* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ResultLogin>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ResultLogin& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ResultLogin& from) {
    ResultLogin::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResultLogin* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ProtocolServerToClient.ResultLogin";
  }
  protected:
  explicit ResultLogin(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMSuccessFieldNumber = 1,
    kMPlayerCountFieldNumber = 2,
  };
  // bool m_success = 1;
  void clear_m_success();
  bool m_success() const;
  void set_m_success(bool value);
  private:
  bool _internal_m_success() const;
  void _internal_set_m_success(bool value);
  public:

  // int32 m_playerCount = 2;
  void clear_m_playercount();
  int32_t m_playercount() const;
  void set_m_playercount(int32_t value);
  private:
  int32_t _internal_m_playercount() const;
  void _internal_set_m_playercount(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ProtocolServerToClient.ResultLogin)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool m_success_;
    int32_t m_playercount_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ProtocolServerToClient_2eproto;
};
// -------------------------------------------------------------------

class ResultCreateAccount final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ProtocolServerToClient.ResultCreateAccount) */ {
 public:
  inline ResultCreateAccount() : ResultCreateAccount(nullptr) {}
  ~ResultCreateAccount() override;
  explicit PROTOBUF_CONSTEXPR ResultCreateAccount(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ResultCreateAccount(const ResultCreateAccount& from);
  ResultCreateAccount(ResultCreateAccount&& from) noexcept
    : ResultCreateAccount() {
    *this = ::std::move(from);
  }

  inline ResultCreateAccount& operator=(const ResultCreateAccount& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResultCreateAccount& operator=(ResultCreateAccount&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ResultCreateAccount& default_instance() {
    return *internal_default_instance();
  }
  static inline const ResultCreateAccount* internal_default_instance() {
    return reinterpret_cast<const ResultCreateAccount*>(
               &_ResultCreateAccount_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ResultCreateAccount& a, ResultCreateAccount& b) {
    a.Swap(&b);
  }
  inline void Swap(ResultCreateAccount* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResultCreateAccount* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ResultCreateAccount* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ResultCreateAccount>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ResultCreateAccount& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ResultCreateAccount& from) {
    ResultCreateAccount::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResultCreateAccount* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ProtocolServerToClient.ResultCreateAccount";
  }
  protected:
  explicit ResultCreateAccount(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMSuccessFieldNumber = 1,
  };
  // bool m_success = 1;
  void clear_m_success();
  bool m_success() const;
  void set_m_success(bool value);
  private:
  bool _internal_m_success() const;
  void _internal_set_m_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:ProtocolServerToClient.ResultCreateAccount)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool m_success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ProtocolServerToClient_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ResultLogin

// bool m_success = 1;
inline void ResultLogin::clear_m_success() {
  _impl_.m_success_ = false;
}
inline bool ResultLogin::_internal_m_success() const {
  return _impl_.m_success_;
}
inline bool ResultLogin::m_success() const {
  // @@protoc_insertion_point(field_get:ProtocolServerToClient.ResultLogin.m_success)
  return _internal_m_success();
}
inline void ResultLogin::_internal_set_m_success(bool value) {
  
  _impl_.m_success_ = value;
}
inline void ResultLogin::set_m_success(bool value) {
  _internal_set_m_success(value);
  // @@protoc_insertion_point(field_set:ProtocolServerToClient.ResultLogin.m_success)
}

// int32 m_playerCount = 2;
inline void ResultLogin::clear_m_playercount() {
  _impl_.m_playercount_ = 0;
}
inline int32_t ResultLogin::_internal_m_playercount() const {
  return _impl_.m_playercount_;
}
inline int32_t ResultLogin::m_playercount() const {
  // @@protoc_insertion_point(field_get:ProtocolServerToClient.ResultLogin.m_playerCount)
  return _internal_m_playercount();
}
inline void ResultLogin::_internal_set_m_playercount(int32_t value) {
  
  _impl_.m_playercount_ = value;
}
inline void ResultLogin::set_m_playercount(int32_t value) {
  _internal_set_m_playercount(value);
  // @@protoc_insertion_point(field_set:ProtocolServerToClient.ResultLogin.m_playerCount)
}

// -------------------------------------------------------------------

// ResultCreateAccount

// bool m_success = 1;
inline void ResultCreateAccount::clear_m_success() {
  _impl_.m_success_ = false;
}
inline bool ResultCreateAccount::_internal_m_success() const {
  return _impl_.m_success_;
}
inline bool ResultCreateAccount::m_success() const {
  // @@protoc_insertion_point(field_get:ProtocolServerToClient.ResultCreateAccount.m_success)
  return _internal_m_success();
}
inline void ResultCreateAccount::_internal_set_m_success(bool value) {
  
  _impl_.m_success_ = value;
}
inline void ResultCreateAccount::set_m_success(bool value) {
  _internal_set_m_success(value);
  // @@protoc_insertion_point(field_set:ProtocolServerToClient.ResultCreateAccount.m_success)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProtocolServerToClient

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ProtocolServerToClient_2eproto
